### ISSUE TITLE
[Feature]: homepage- blog post 

### ISSUE THREAD

**Issue by omuwa-123** [AIforblog/aiblogfrontend#35]
### Description

as an unauthenticated user, i want to be able to view the blog post display so that i can view but cant publish

### Acceptance Criteria

- blog post should be displayed in a visually appealing grid layout, ensuring optimal spacing and readability. 
- the blog post display should align with the overall design and branding of the website.
- the layout should adapt gracefully to different screen sizes and devices
- the design should use high quality images, clear typography and consistent styling to create an engaging and visually appealing user experience.

### Links

| [`FIGMA LINK`](LINK_HERE)
https://www.figma.com/design/7DGLgn48eyVicv8JpkPchw/dRello?node-id=826-10895&t=pEtrUI7ZWUkGkNhr-4

### Images

![image](URL_HERE)

**Comment by RitaMonye** [comment]
Have you started working on this? @FutureAtPivot 
The dashboard layout was equally created, have you reviewed it?

**Comment by emmanuelchika** [comment]
Let me check it out now.
