### ISSUE TITLE
[Feature]: Implement Job Reader Page

### ISSUE THREAD

**Issue by Beulah94** [AIforblog/aiblogfrontend#66]
### Description

Create a detailed page for displaying job listings. The page should include the job title, job description, application deadline, Start and end date, payment, and a "Apply Now" button.

### Acceptance Criteria

- The page should have a clear and concise layout.
- The job title, company, location, salary range, and application deadline should be prominently displayed.
- The job description should be well-formatted and easy to read.
- Users should be be able to comment, like and share
- The "Apply Now" button should link to the appropriate application form or process.
- The page should be responsive and adapt to different screen sizes.

### Links

| [`FIGMA LINK`](LINK_HERE)
https://www.figma.com/design/7DGLgn48eyVicv8JpkPchw/dRello?node-id=1205-18805&t=Mk4zbLATKtTZPqmO-4

### Images

![image](URL_HERE)

**Comment by RitaMonye** [comment]
@Maiqel1 please delete and add anything missing in the other ticket from here to there. Thank you
